// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmtlizavsjyvvvittkfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtdGxpemF2c2p5dnZ2aXR0a2ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjY1MzYsImV4cCI6MjA3MDg0MjUzNn0.NnHoH31N8a98hhFlkUFNewTtHuMDXNQeE12XxibsldU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});